### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [demirj/gtm-seo-monitoring-title-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [url](https://github.com/demirj/gtm-templates/blob/main/seo-monitoring-title/README.md) mentioned in the metadata file is showing "Page not found" error.
![Screenshot 2021-10-12 11 16 19 AM](https://user-images.githubusercontent.com/53495700/137008325-babe2e97-df2d-466c-b537-d7bb8a2ebe3d.png)

**Comment by demirj** [comment]
Thanks for the feedback - issue is fixed.
